import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AuthProviders from "./provider";
import Layout from "@/component/Layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <AuthProviders>
            <Layout>{children}</Layout>
          </AuthProviders>
        </AntdRegistry>
      </body>
    </html>
  );
}
